---
kind: pipeline
name: testing-windows-amd64

platform:
  os: windows
  arch: amd64
  version: 1903

steps:
- name: tests
  image: golang:1.13
  volumes:
  - name: deps
    path: /go
  commands:
    - go mod download
    - go test ./...
    - go build .

trigger:
  event:
    include:
    - push
    - pull_request
    - tag

volumes:
- name: deps
  temp: {}


---
kind: pipeline
name: testing-linux-arm64

platform: 
  os: linux
  arch: arm64

steps:
- name: tests
  image: golang:1.13
  volumes:
  - name: deps
    path: /go
  commands:
    - go mod download
    - go test ./...
    - go build .


trigger:
  event:
    include:
    - push
    - pull_request
    - tag

volumes:
- name: deps
  temp: {}


---
kind: pipeline
name: testing-linux-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: tests
  image: golang:1.13
  volumes:
  - name: deps
    path: /go
  commands:
  - go mod download
  - go test ./...
  - go build .

trigger:
  event:
    include:
    - push
    - pull_request
    - tag

volumes:
- name: deps
  temp: {}


---
kind: pipeline
name: release

platform:
  os: linux
  arch: amd64

trigger:
  event:
    - tag
  
depends_on: 
  - testing-linux-amd64
  - testing-linux-arm64
  - testing-windows-amd64

steps:
- name: fetch
  image: docker:git
  commands:
    - git fetch --tags

- name: release
  image: golang
  environment:
    GITHUB_TOKEN:
      from_secret: github_token
  volumes:
    - name: deps
      path: /go
  commands:
    - curl -sL https://git.io/goreleaser | bash
  when:
    event: tag

volumes:
- name: deps
  temp: {}

