project_name: test

# This is an example goreleaser.yaml file with some sane defaults.

# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod download
builds:
  - id: default
    goos:
      - linux
      - windows
    goarch:
      - amd64
archives:
  - replacements:
      linux: Linux
      windows: Windows
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
