project_name: jellycli

before:
  hooks:
    - go mod download
builds:
  - id: linux-amd64
    goos:
      - linux
    goarch:
      - amd64
  - id: windows
    env:
      - CGO_ENABLED=1
    goos:
      - windows
    goarch:
      - amd64
archives:
  - id: default
    replacements:
      linux: Linux
      windows: Windows
      amd64: x86_64
    format_overrides:
      - goos: linux
        format: binary
      - goos: windows
        format: binary

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  skip: false
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  draft: true
  prerelease: auto

